# Generated by Django 5.0.3 on 2024-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_usuario_delete_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
    ]
